### PR TITLE
Update ctags binary

### PR DESCRIPTION
**Pull request by hovsater**
This pull request updates the `ctags` binary to the latest version, `Universal Ctags 5.9.0(81a7010d), Copyright (C) 2015 Universal Ctags Team`. It also updates `tmtags` to use the appropriate flags.

### CODE REVIEW

**Comment by infininight** [comment]
I haven't got to the point of getting this setup to test but get an error when I just try to run the command without setup:

```
dyld: Library not loaded: /usr/local/opt/jansson/lib/libjansson.4.dylib
Referenced from: /Users/msheets/Library/Application Support/TextMate/Bundles/ctags.tmbundle/Support/bin/ctags-objc
Reason: image not found
```

**Comment by kevinsjoberg** [comment]
@infininight oh, I see. I guess the libraries have to be statically linked. I'll give it another look!

**Comment by kevinsjoberg** [comment]
@infininight I've updated the binary again. Running `otool -L Support/bin/ctags-objc` now give me:

```console
Support/bin/ctags-objc:
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
```

which looks much better than before.

**Full Disclosure**

I wasn't sure how to proceed to built a statically linked version of the binary so I asked for help here, https://github.com/universal-ctags/ctags/discussions/2977. I then followed the instructions posted by @ leleliu008 here, https://github.com/universal-ctags/ctags/discussions/2977#discussioncomment-668677.

The binary seem to be working just fine. Feel free to test it out yourself.

**Comment by leleliu008** [comment]
> @infininight I've updated the binary again. Running `otool -L Support/bin/ctags-objc` now give me:
> 
> ```
> Support/bin/ctags-objc:
> 	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.11)
> 	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0)
> 	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.60.1)
> ```
> 
> which looks much better than before.
> 
> **Full Disclosure**
> 
> I wasn't sure how to proceed to built a statically linked version of the binary so I asked for help here, [universal-ctags/ctags#2977](https://github.com/universal-ctags/ctags/discussions/2977). I then followed the instructions posted by @leleliu008 here, [universal-ctags/ctags#2977 (reply in thread)](https://github.com/universal-ctags/ctags/discussions/2977#discussioncomment-668677).
> 
> The binary seem to be working just fine. Feel free to test it out yourself.

**/usr/lib/libz.1.dylib** and **/usr/lib/libiconv.2.dylib** are pre-installed by macOS itself. these API is very stable. so don't worry.

**Pull request merged**
